### ISSUE TITLE
Add SVTYPE in the INFO column

### ISSUE THREAD

**Issue by soymintc** [cortes-ciriano-lab/savana#8]
Although the user could figure out what SVTYPE (according to [VCF specs](https://samtools.github.io/hts-specs/VCFv4.2.pdf)) each SV is, I think it would be better and error-prone if SAVANA could describe the SVTYPE for each SV

**Comment by helrick** [comment]
Hi there, thanks for the suggestion! I've implemented this in [PR #12](https://github.com/cortes-ciriano-lab/savana/pull/12), but am calling everything BND except for insertions (INS) because without copy number information, it's not possible to definitively call a SVTYPE (in VCFv4.2). GRIDSS has a more in depth explanation for their decision to do this here: https://github.com/PapenfussLab/gridss#why-are-all-calls-bnd.

Currently SAVANA implements VCFv4.2 as its output format, but I will look into implementing the newly released [v4.4](https://github.com/samtools/hts-specs/blob/master/VCFv4.4.pdf) in future which should allow us to capture and report this. 

For now, we report the breakend orientation using brackets in the ALT field as described in section 5.4 of [VCFv4.2](https://samtools.github.io/hts-specs/VCFv4.2.pdf). We also report this in a "BP_NOTATION" field which can be converted to different nomenclatures as follows:

|Nomenclature  | Deletion-like | Duplication-like  | Head-to-head Inversion  | Tail-to-tail Inversion  |
| ------------------- | ----------------- | --------------------- |  ------------------------------- |  -------------------------- |
| BP_NOTATION  | +- | -+ | ++ | -- |
| Brackets (VCF)  | N[chr:pos[ / ]chr:pos]N | ]chr:pos]N / N[chr:pos[ | N]chr:pos] / N]chr:pos] | [chr:pos[N / [chr:pos[N |
| 5' to 3'  | 3to5 | 5to3 | 3to3 | 5to5|

**Comment by soymintc** [comment]
@helrick Thanks!! Realized that `SVTYPE` will be deprecated in VCF v4.4!
